version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "5000:5000"
    nginx:
        restart: Unless Stopped
        build:
            context: ./nginx
        ports:
            - "80:80"